[versions]
# 核心库
agp = "8.4.0-alpha13"
kotlin = "1.9.22"
compose-bom = "2024.03.00"
core-ktx = "1.12.0"
lifecycle-runtime-ktx = "2.7.0"
activity-compose = "1.8.2"

# 官方库
accompanist-permissions = "0.32.0"
biometric = "1.2.0-alpha05"
camerax = "1.3.2"
coil-compose = "2.5.0"
material-icons-extended = "1.6.4"
navigation-compose = "2.7.7"
room = "2.6.1"
ksp = "1.9.22-1.0.17"
# 测试相关
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"

# 三方库
amap-search = "9.7.0"
amap = "9.8.3"
lunar = "1.6.3"
pinyin = "0.4.0"
reorderable = "0.9.6"
retrofit = "2.9.0"
mlkit = "17.2.0"
zxing-core = "3.4.1"

[libraries]
# 核心库
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" } # 支持kotlin
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" } # 组件支持生命周期管理
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" } # 支持在activity中嵌入compose组件
ui = { module = "androidx.compose.ui:ui" }
ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" } # 统一管理compose相关依赖版本

# 官方库
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-runtime-ktx" } # 支持viewmodel
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" } # 支持组件间导航
material3 = { module = "androidx.compose.material3:material3" } # material3风格的官方组件库及主题
material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "material-icons-extended" } # icon扩展库
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist-permissions" } # 简化权限请求
androidx-biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" } # 简化生物认证
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camerax" } # 简化相机调用
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camerax" } # 相机生命周期管理
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "camerax" } # 相机视图容器
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" } # 简化数据库访问
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" } # room支持kotlin
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" } # room支持根据注解自动生成对应实现
# 调试相关
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" } # 支持compose组件预览
# 测试相关
junit = { module = "junit:junit", version.ref = "junit" }
ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }

# 三方库
lunar = { module = "cn.6tail:lunar", version.ref = "lunar" } # 计算农历日期与节日
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" } # 支持异步加载图片
pinyin = { module = "com.github.houbb:pinyin", version.ref = "pinyin" } # 汉字转拼音
reorderable = { module = "org.burnoutcrew.composereorderable:reorderable", version.ref = "reorderable" } # 支持拖拽排序
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" } # 网络请求库
retrofit-converter = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" } # 支持网络响应结果转为指定类对象
amap = { module = "com.amap.api:3dmap", version.ref = "amap" } # 高德地图
amap-search = { module = "com.amap.api:search", version.ref = "amap-search" } # 地图支持搜索
zxing-core = { module = "com.google.zxing:core", version.ref = "zxing-core" } # 二维码生成/识别（效率低）
mlkit-barcode-scanning = { module = "com.google.mlkit:barcode-scanning", version.ref = "mlkit" } # 二维码识别（基于机器学习）

[plugins]
com-android-application = { id = "com.android.application", version.ref = "agp" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
com-google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
android-library = { id = "com.android.library", version.ref = "agp" }

[bundles]
camerax = ["androidx-camera-camera2", "androidx-camera-lifecycle", "androidx-camera-view"]
retrofit = ["retrofit", "retrofit-converter"]